### ISSUE TITLE
Project poster missing

### ISSUE THREAD

**Issue by kanishkanarch** [thecountoftuscany/crazyflie-run-and-tumble#1]

**Comment by thecountoftuscany** [comment]
Hi,
The poster was removed during a major overhaul of the repository, since this project has evolved a lot from the time it was just a course project. A lot has changed since the README was written (eg. we are no longer using the ROS library and instead just using the python bindings from [crazyflie-lib-python](https://github.com/bitcraze/crazyflie-lib-python)). I just haven't had the time to update the README yet. If you have any specific questions about how any of this was implemented, feel free to ask, though I think most of the code is self-explanatory. You can still access the project poster from [this commit](https://github.com/thecountoftuscany/crazyflie-run-and-tumble/blob/ca5551c61cfac40ec27befd05dfa0bb7c93e0499/documents/Project-Final_Poster.pdf) or any other previous commit.
